# Generated by Django 5.1.4 on 2025-01-08 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=15, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('branch', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HostelDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('hostel_name', models.CharField(max_length=100)),
                ('warden_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('registration_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sggs.student')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=100)),
                ('participation_date', models.DateField()),
                ('achievement', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sggs.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10)),
                ('faculty', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('registration_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sggs.student')),
            ],
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], max_length=10)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('registration_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sggs.student')),
            ],
        ),
    ]
